[dmenu]
# -fn : шрифт
# -nb : колір фону (темний)
# -nf : колір тексту (бежевий)
# -sb : колір вибраного пункту (помаранчевий)
# -sf : колір тексту у вибраному пункті (темний)
dmenu_command = rofi -dmenu -width 25 -location 3 -yoffset 35 -xoffset -10 -p "Wi-Fi" -theme-str 'window { border: 2px; border-color: #ff9e64; border-radius: 10px; font: "JetBrainsMono Nerd Font 11"; }'

[dmenu_passphrase]
# Для вікна введення пароля (використовуємо зірочки)
# dmenu_command = dmenu -P

[editor]
terminal = alacritty
gui_if_available = True
