#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# --- AUTOSTART ---

# Статичні шпалери за замовчуванням
feh --bg-fill ~/Wallpapers/static/test.jpg &

# Запуск композитора
pkill picom
picom -b &

pkill -x polybar
pkill -x eww

~/.config/polybar/launch.sh &
eww & daemon


Bluetooth
setxkbmap -layout us,ua -option grp:alt_shift_toggle &

eww daemon &
eww open bar &

blueman-applet &

dunst &

~/.config/bspwm/scripts/wall_toggle.sh &
